"""fix_user_profile_columns

Revision ID: f3187a03f702
Revises: 15ae02c055c6
Create Date: 2026-03-31 08:35:35.797670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3187a03f702'
down_revision: Union[str, Sequence[str], None] = '15ae02c055c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_protein', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target_carbs', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('target_fat', sa.Float(), nullable=True))
    op.alter_column('users', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'daily_protein_target')
    op.drop_column('users', 'daily_carbs_target')
    op.drop_column('users', 'daily_fat_target')
    op.alter_column('weight_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_weight_logs_user_date'), 'weight_logs', type_='unique')
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.create_unique_constraint(op.f('uq_weight_logs_user_date'), 'weight_logs', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('weight_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('daily_fat_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('daily_carbs_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('daily_protein_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('users', 'onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'target_fat')
    op.drop_column('users', 'target_carbs')
    op.drop_column('users', 'target_protein')
    # ### end Alembic commands ###
